version: '3.9'

services:
  api_eventos:
    build: ../api_service
    ports:
      - "5000:5000"
    depends_on:
      - api_database
    volumes:
      - instance-data:/app/instance
    networks:
      - appnetwork

  api_database:
    build: ../api_database
    volumes:
      - database-data:/app/data
      - instance-data:/app/instance
    ports:
      - "5001:5001"
    networks:
      - appnetwork

volumes:
  database-data:
  instance-data:

networks:
  appnetwork:
    driver: bridge
